# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pantalla_calculo.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1531, 734)
        MainWindow.setMinimumSize(QSize(700, 498))
        MainWindow.setStyleSheet(u"QMainWindow{\n"
"background-color: rgb(250, 220, 255);\n"
"}\n"
"")
        MainWindow.setAnimated(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.boton_calc = QPushButton(self.centralwidget)
        self.boton_calc.setObjectName(u"boton_calc")
        self.boton_calc.setGeometry(QRect(40, 60, 141, 41))
        font = QFont()
        font.setPointSize(10)
        self.boton_calc.setFont(font)
        self.boton_calc.setAutoDefault(False)
        self.apellidos = QLineEdit(self.centralwidget)
        self.apellidos.setObjectName(u"apellidos")
        self.apellidos.setGeometry(QRect(610, 10, 281, 31))
        self.apellidos.setFont(font)
        self.nombres = QLineEdit(self.centralwidget)
        self.nombres.setObjectName(u"nombres")
        self.nombres.setGeometry(QRect(170, 10, 311, 31))
        self.nombres.setFont(font)
        self.fecha_nac = QDateEdit(self.centralwidget)
        self.fecha_nac.setObjectName(u"fecha_nac")
        self.fecha_nac.setGeometry(QRect(1160, 10, 161, 31))
        self.fecha_nac.setFont(font)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 10, 111, 31))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(75)
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(490, 10, 121, 31))
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(900, 10, 241, 31))
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(410, 399, 221, 31))
        self.label_4.setFont(font1)
        self.label_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(420, 440, 211, 31))
        self.label_5.setFont(font1)
        self.label_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.ciclo_letras = QLabel(self.centralwidget)
        self.ciclo_letras.setObjectName(u"ciclo_letras")
        self.ciclo_letras.setGeometry(QRect(640, 400, 61, 31))
        palette = QPalette()
        brush = QBrush(QColor(255, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(120, 120, 120, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.ciclo_letras.setPalette(palette)
        self.ciclo_letras.setFont(font1)
        self.clave_personal = QLabel(self.centralwidget)
        self.clave_personal.setObjectName(u"clave_personal")
        self.clave_personal.setGeometry(QRect(640, 440, 61, 31))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.clave_personal.setPalette(palette1)
        self.clave_personal.setFont(font1)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(130, 130, 171, 41))
        self.label_6.setFont(font1)
        self.label_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(140, 190, 161, 41))
        self.label_7.setFont(font1)
        self.label_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 250, 281, 41))
        self.label_8.setFont(font1)
        self.label_8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.esencia = QLabel(self.centralwidget)
        self.esencia.setObjectName(u"esencia")
        self.esencia.setGeometry(QRect(310, 130, 1001, 41))
        self.esencia.setFont(font1)
        self.esencia.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.imagen = QLabel(self.centralwidget)
        self.imagen.setObjectName(u"imagen")
        self.imagen.setGeometry(QRect(310, 190, 1001, 41))
        self.imagen.setFont(font1)
        self.imagen.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.sendero_mun = QLabel(self.centralwidget)
        self.sendero_mun.setObjectName(u"sendero_mun")
        self.sendero_mun.setGeometry(QRect(310, 250, 1001, 41))
        self.sendero_mun.setFont(font1)
        self.sendero_mun.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.total = QLabel(self.centralwidget)
        self.total.setObjectName(u"total")
        self.total.setGeometry(QRect(310, 300, 1001, 31))
        self.total.setMaximumSize(QSize(16777215, 16777215))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.total.setPalette(palette2)
        font2 = QFont()
        font2.setPointSize(7)
        font2.setBold(True)
        font2.setWeight(75)
        self.total.setFont(font2)
        self.total.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(70, 400, 191, 31))
        self.label_9.setFont(font1)
        self.label_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(110, 440, 151, 31))
        self.label_10.setFont(font1)
        self.label_10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sendero_nat = QLabel(self.centralwidget)
        self.sendero_nat.setObjectName(u"sendero_nat")
        self.sendero_nat.setGeometry(QRect(270, 395, 81, 31))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.sendero_nat.setPalette(palette3)
        self.sendero_nat.setFont(font1)
        self.potencial = QLabel(self.centralwidget)
        self.potencial.setObjectName(u"potencial")
        self.potencial.setGeometry(QRect(270, 440, 111, 31))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.potencial.setPalette(palette4)
        self.potencial.setFont(font1)
        self.sendero_nat_k = QLabel(self.centralwidget)
        self.sendero_nat_k.setObjectName(u"sendero_nat_k")
        self.sendero_nat_k.setGeometry(QRect(360, 395, 41, 31))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.sendero_nat_k.setPalette(palette5)
        self.sendero_nat_k.setFont(font1)
        self.clave_personal_2 = QLabel(self.centralwidget)
        self.clave_personal_2.setObjectName(u"clave_personal_2")
        self.clave_personal_2.setGeometry(QRect(870, 525, 111, 21))
        self.clave_personal_2.setFont(font1)
        self.etapa_1 = QLabel(self.centralwidget)
        self.etapa_1.setObjectName(u"etapa_1")
        self.etapa_1.setGeometry(QRect(750, 560, 151, 31))
        self.etapa_1.setFont(font1)
        self.etapa_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.etapa_2 = QLabel(self.centralwidget)
        self.etapa_2.setObjectName(u"etapa_2")
        self.etapa_2.setGeometry(QRect(750, 590, 151, 31))
        self.etapa_2.setFont(font1)
        self.etapa_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.etapa_3 = QLabel(self.centralwidget)
        self.etapa_3.setObjectName(u"etapa_3")
        self.etapa_3.setGeometry(QRect(750, 620, 151, 31))
        self.etapa_3.setFont(font1)
        self.etapa_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.etapa_4 = QLabel(self.centralwidget)
        self.etapa_4.setObjectName(u"etapa_4")
        self.etapa_4.setGeometry(QRect(750, 650, 151, 31))
        self.etapa_4.setFont(font1)
        self.etapa_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.etapa_1_v = QLabel(self.centralwidget)
        self.etapa_1_v.setObjectName(u"etapa_1_v")
        self.etapa_1_v.setGeometry(QRect(910, 560, 41, 21))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.etapa_1_v.setPalette(palette6)
        self.etapa_1_v.setFont(font1)
        self.etapa_2_v = QLabel(self.centralwidget)
        self.etapa_2_v.setObjectName(u"etapa_2_v")
        self.etapa_2_v.setGeometry(QRect(910, 590, 41, 21))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.etapa_2_v.setPalette(palette7)
        self.etapa_2_v.setFont(font1)
        self.etapa_3_v = QLabel(self.centralwidget)
        self.etapa_3_v.setObjectName(u"etapa_3_v")
        self.etapa_3_v.setGeometry(QRect(910, 620, 41, 21))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.etapa_3_v.setPalette(palette8)
        self.etapa_3_v.setFont(font1)
        self.etapa_4_v = QLabel(self.centralwidget)
        self.etapa_4_v.setObjectName(u"etapa_4_v")
        self.etapa_4_v.setGeometry(QRect(910, 650, 41, 21))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.etapa_4_v.setPalette(palette9)
        self.etapa_4_v.setFont(font1)
        self.clave_personal_3 = QLabel(self.centralwidget)
        self.clave_personal_3.setObjectName(u"clave_personal_3")
        self.clave_personal_3.setGeometry(QRect(30, 540, 161, 41))
        self.clave_personal_3.setFont(font1)
        self.anio = QLineEdit(self.centralwidget)
        self.anio.setObjectName(u"anio")
        self.anio.setGeometry(QRect(210, 540, 121, 41))
        self.anio.setFont(font)
        self.boton_calc_anio = QPushButton(self.centralwidget)
        self.boton_calc_anio.setObjectName(u"boton_calc_anio")
        self.boton_calc_anio.setGeometry(QRect(360, 540, 141, 41))
        self.boton_calc_anio.setFont(font)
        self.boton_calc_anio.setAutoDefault(False)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 660, 181, 31))
        self.label_15.setFont(font1)
        self.label_15.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 619, 171, 21))
        self.label_16.setFont(font1)
        self.label_16.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.anio_personal = QLabel(self.centralwidget)
        self.anio_personal.setObjectName(u"anio_personal")
        self.anio_personal.setGeometry(QRect(190, 610, 151, 31))
        self.anio_personal.setFont(font1)
        self.anio_personal.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.digito_edad = QLabel(self.centralwidget)
        self.digito_edad.setObjectName(u"digito_edad")
        self.digito_edad.setGeometry(QRect(190, 660, 151, 31))
        self.digito_edad.setFont(font1)
        self.digito_edad.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.anio_personal_v = QLabel(self.centralwidget)
        self.anio_personal_v.setObjectName(u"anio_personal_v")
        self.anio_personal_v.setGeometry(QRect(350, 610, 41, 31))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.anio_personal_v.setPalette(palette10)
        self.anio_personal_v.setFont(font1)
        self.digito_edad_v = QLabel(self.centralwidget)
        self.digito_edad_v.setObjectName(u"digito_edad_v")
        self.digito_edad_v.setGeometry(QRect(350, 660, 41, 31))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.digito_edad_v.setPalette(palette11)
        self.digito_edad_v.setFont(font1)
        self.ingrese_anio = QLabel(self.centralwidget)
        self.ingrese_anio.setObjectName(u"ingrese_anio")
        self.ingrese_anio.setGeometry(QRect(20, 590, 421, 20))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.ingrese_anio.setPalette(palette12)
        self.ingrese_anio.setFont(font1)
        self.ingrese_nombre = QLabel(self.centralwidget)
        self.ingrese_nombre.setObjectName(u"ingrese_nombre")
        self.ingrese_nombre.setGeometry(QRect(200, 60, 711, 20))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.ingrese_nombre.setPalette(palette13)
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        font3.setWeight(75)
        self.ingrese_nombre.setFont(font3)
        self.clave_personal_5 = QLabel(self.centralwidget)
        self.clave_personal_5.setObjectName(u"clave_personal_5")
        self.clave_personal_5.setGeometry(QRect(720, 410, 271, 41))
        self.clave_personal_5.setFont(font1)
        self.clave_personal_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lecciones_karmicas = QLabel(self.centralwidget)
        self.lecciones_karmicas.setObjectName(u"lecciones_karmicas")
        self.lecciones_karmicas.setGeometry(QRect(1000, 420, 511, 31))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.lecciones_karmicas.setPalette(palette14)
        self.lecciones_karmicas.setFont(font1)
        self.salir = QPushButton(self.centralwidget)
        self.salir.setObjectName(u"salir")
        self.salir.setGeometry(QRect(1220, 660, 151, 41))
        self.salir.setFont(font)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-10, 510, 531, 21))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(510, 520, 20, 181))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.nombres, self.apellidos)
        QWidget.setTabOrder(self.apellidos, self.fecha_nac)
        QWidget.setTabOrder(self.fecha_nac, self.boton_calc)
        QWidget.setTabOrder(self.boton_calc, self.anio)
        QWidget.setTabOrder(self.anio, self.boton_calc_anio)

        self.retranslateUi(MainWindow)

        self.boton_calc.setDefault(False)
        self.boton_calc_anio.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Numerologia", None))
        self.boton_calc.setText(QCoreApplication.translate("MainWindow", u"Calcular", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Nombres:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Apellidos:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Fecha de Nacimiento:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Ciclo de Letras =", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Clave Personal =", None))
        self.ciclo_letras.setText("")
        self.clave_personal.setText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Esencia:", None))
#if QT_CONFIG(tooltip)
        self.label_7.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Imagen:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Sendero del Mundo:", None))
        self.esencia.setText("")
        self.imagen.setText("")
        self.sendero_mun.setText("")
        self.total.setText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Sendero Natal:", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Potencial:", None))
        self.sendero_nat.setText("")
        self.potencial.setText("")
        self.sendero_nat_k.setText("")
        self.clave_personal_2.setText(QCoreApplication.translate("MainWindow", u"Etapas", None))
        self.etapa_1.setText(QCoreApplication.translate("MainWindow", u"De 00 a 35 =", None))
        self.etapa_2.setText(QCoreApplication.translate("MainWindow", u"De 36 a 45 =", None))
        self.etapa_3.setText(QCoreApplication.translate("MainWindow", u"De 46 a 55 =", None))
        self.etapa_4.setText(QCoreApplication.translate("MainWindow", u"De 56 a ...  =", None))
        self.etapa_1_v.setText("")
        self.etapa_2_v.setText("")
        self.etapa_3_v.setText("")
        self.etapa_4_v.setText("")
        self.clave_personal_3.setText(QCoreApplication.translate("MainWindow", u"A\u00f1o en Curso", None))
        self.boton_calc_anio.setText(QCoreApplication.translate("MainWindow", u"Calcular", None))
#if QT_CONFIG(tooltip)
        self.label_15.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"D\u00edgito de edad", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"A\u00f1o personal", None))
        self.anio_personal.setText("")
        self.digito_edad.setText("")
        self.anio_personal_v.setText("")
        self.digito_edad_v.setText("")
        self.ingrese_anio.setText("")
        self.ingrese_nombre.setText("")
        self.clave_personal_5.setText(QCoreApplication.translate("MainWindow", u"Lecciones K\u00e1rmicas =", None))
        self.lecciones_karmicas.setText("")
        self.salir.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
    # retranslateUi

